# Alucar - Analisando as vendas

In [33]:
import pandas as pd

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import r2_score

In [35]:
dados =  pd.read_csv('dados/stores-datas-regression.csv', sep = ',')

In [36]:
dados.head(10)

,Order Number,Line Number,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Unit Price,Net Price,Unit Cost,Currency Code,Exchange Rate,Sale Days,Sale Years,Delivery Time,d_Stores.Square Meters,d_Stores.Status
0,270302,0,26/05/2017,26/05/2017,1528440,450,2105,1,132750,126113,43983,USD,10000,2430,"6,657534247",0,2000,Open
1,271000,0,02/06/2017,02/06/2017,1976114,500,2018,1,8549,8122,4359,USD,10000,2423,"6,638356164",0,2000,Open
2,272101,0,13/06/2017,13/06/2017,2072388,630,1609,1,33799,29405,11198,USD,10000,2412,"6,608219178",0,2000,Open
3,272203,0,14/06/2017,14/06/2017,1242570,630,1498,1,42000,40740,19314,USD,10000,2411,"6,605479452",0,2000,Open
4,272900,0,21/06/2017,21/06/2017,1564654,440,1352,1,3219,3058,1480,USD,10000,2404,"6,58630137",0,2000,Open
5,272902,0,21/06/2017,21/06/2017,1665483,450,1791,1,3870,3444,1973,USD,10000,2404,"6,58630137",0,2000,Open
6,273703,0,29/06/2017,29/06/2017,1715789,500,1592,1,2339,2339,1075,USD,10000,2396,"6,564383562",0,2000,Open
7,273802,0,30/06/2017,30/06/2017,1676996,450,1629,1,1299,1299,662,USD,10000,2395,"6,561643836",0,2000,Open
8,274301,0,05/07/2017,05/07/2017,1851215,450,1599,1,7524,6922,3461,USD,10000,2390,"6,547945205",0,2000,Open
9,274500,0,07/07/2017,07/07/2017,1244856,610,1801,1,2880,2621,1468,USD,10000,2388,"6,542465753",0,2000,Open

In [37]:
features = ['Net Price', 'd_Stores.Square Meters', 'Quantity', 'Unit Price', 'Unit Cost', 'StoreKey']
X = dados[features]
y = dados['d_Stores.Status']
X['Store_ID'] = dados['StoreKey']  # Adicionando a coluna 'StoreKey' ao conjunto de características

C:\Users\Elaine\AppData\Local\Temp\ipykernel_9444\1278373046.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Store_ID'] = dados['StoreKey']  # Adicionando a coluna 'StoreKey' ao conjunto de características

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:
modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [40]:
previsoes = modelo.predict(X_test)

In [41]:
acuracia = accuracy_score(y_test, previsoes)
matriz_confusao = confusion_matrix(y_test, previsoes)

print(f'Acurácia do modelo: {acuracia}')
print('Matriz de Confusão:')
print(matriz_confusao)

Acurácia do modelo: 1.0
Matriz de Confusão:
[[  53    0    0]
 [   0 1118    0]
 [   0    0   11]]

In [42]:
resultados_df = pd.DataFrame({'StoreKey': X_test['Store_ID'], 'Real': y_test, 'Previsto': previsoes})

In [67]:
resultados_df.to_csv('dados/resultados_modelo.csv', index=False)

In [66]:
resultados_df .head(100)

      StoreKey  Real Previsto
3491        35  Open     Open
5261       220  Open     Open
1425       470  Open     Open
5732       255  Open     Open
439        630  Open     Open
...        ...   ...      ...
960        540  Open     Open
4630       100  Open     Open
5907       270  Open     Open
805        610  Open     Open
2259       585  Open     Open

[100 rows x 3 columns]

In [68]:
import nbformat

# Substitua 'seu_notebook.ipynb' pelo caminho do seu Jupyter Notebook
notebook_path = 'vendas-regression.ipynb'

# Leitura do conteúdo do notebook
with open(notebook_path, 'r', encoding='utf-8') as notebook_file:
    notebook_content = nbformat.read(notebook_file, as_version=4)

# Extração do código de todas as células de código
codigo_do_notebook = []
for cell in notebook_content.cells:
    if cell.cell_type == 'code':
        codigo_do_notebook.append(cell.source)

# Junte todo o código em uma única string
codigo_completo = '\n\n'.join(codigo_do_notebook)

# Agora, você pode imprimir o código ou salvá-lo em um arquivo
print(codigo_completo)

# Exemplo de salvar o código em um arquivo
with open('codigo_completo.py', 'w', encoding='utf-8') as output_file:
    output_file.write(codigo_completo)

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import r2_score

dados =  pd.read_csv('dados/stores-datas-regression.csv', sep = ',')

dados.head(10)

features = ['Net Price', 'd_Stores.Square Meters', 'Quantity', 'Unit Price', 'Unit Cost', 'StoreKey']
X = dados[features]
y = dados['d_Stores.Status']
X['Store_ID'] = dados['StoreKey']  # Adicionando a coluna 'StoreKey' ao conjunto de características


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

previsoes = modelo.predict(X_test)

acuracia = accuracy_score(y_test, previsoes)
matriz_confusao = confusion_matrix(y_test, previsoes)

print(f'Acurácia do modelo: {acuracia}')
print('Matriz de Confusão:')
print(matriz_confusao)

resultados_df = pd.DataFrame({'StoreKey': X_test['Store_ID'], 'Real': y_test, 'Previsto': previsoes})

resultados_df.to_csv('dados/resultados_modelo.csv', index=False)

resultados_df .head(100)

In [76]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Carregar os dados
dados = pd.read_csv('dados/stores-datas-regression.csv', sep=',')

# Selecionar características e variável alvo
features = ['Net Price', 'Quantity']
X = dados[features]
y = dados['d_Stores.Status']
X['Store_ID'] = dados['StoreKey']  # Adicionando a coluna 'StoreKey' ao conjunto de características

# Dividir o conjunto de dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criar e treinar o modelo
modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
previsoes = modelo.predict(X_test)

# Calcular a acurácia e matriz de confusão
acuracia = accuracy_score(y_test, previsoes)
matriz_confusao = confusion_matrix(y_test, previsoes)

# Exibir resultados
print(f'Acurácia do modelo: {acuracia}')
print('Matriz de Confusão:')
print(matriz_confusao)

C:\Users\Elaine\AppData\Local\Temp\ipykernel_9444\2738944855.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Store_ID'] = dados['StoreKey']  # Adicionando a coluna 'StoreKey' ao conjunto de características

Acurácia do modelo: 0.9873096446700508
Matriz de Confusão:
[[  42   11    0]
 [   0 1118    0]
 [   0    4    7]]

In [77]:
resultados_df = pd.DataFrame({'StoreKey': X_test['Store_ID'], 'Real': y_test, 'Previsto': previsoes})

In [78]:
resultados_df.head()

      StoreKey  Real Previsto
3491        35  Open     Open
5261       220  Open     Open
1425       470  Open     Open
5732       255  Open     Open
439        630  Open     Open

In [79]:
resultados_df.to_csv('dados/resultados_modelo2.csv', index=False)

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Carregar os dados
dados = pd.read_csv('dados/stores-datas - Página1.csv', sep=',')

# Selecionar características e variável alvo
features = ['revenue', 'cost']
X = dados[features]
y = dados['d_Stores.Status']
X['Store_ID'] = dados['StoreKey']  # Adicionando a coluna 'StoreKey' ao conjunto de características

# Dividir o conjunto de dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criar e treinar o modelo
modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
previsoes = modelo.predict(X_test)

# Calcular a acurácia e matriz de confusão
acuracia = accuracy_score(y_test, previsoes)
matriz_confusao = confusion_matrix(y_test, previsoes)

# Exibir resultados
print(f'Acurácia do modelo: {acuracia}')
print('Matriz de Confusão:')
print(matriz_confusao)

C:\Users\Elaine\AppData\Local\Temp\ipykernel_4104\262681083.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Store_ID'] = dados['StoreKey']  # Adicionando a coluna 'StoreKey' ao conjunto de características

Acurácia do modelo: 0.9898477157360406
Matriz de Confusão:
[[  39    9    0]
 [   0 1124    0]
 [   0    3    7]]

In [2]:
resultados_df = pd.DataFrame({'StoreKey': X_test['Store_ID'], 'Real': y_test, 'Previsto': previsoes})

In [4]:
resultados_df.head(50)

      StoreKey    Real Previsto
3491        60    Open     Open
5261       270    Open     Open
1425       570    Open     Open
5732       320    Open     Open
439        500    Open     Open
5491       220    Open     Open
1319       590    Open     Open
1330       570    Open     Open
5122       240    Open     Open
296        590    Open     Open
5369       320    Open     Open
3460       400    Open     Open
2802       570    Open     Open
2299       660    Open     Open
787        660    Open     Open
5574       240    Open     Open
4230       190    Open     Open
4704       390    Open     Open
2627       585    Open     Open
5837       340    Open     Open
683        480    Open     Open
794        630    Open     Open
4054       340    Open     Open
4507        90    Open     Open
319        530    Open     Open
1074       550    Open     Open
4733       380    Open     Open
5452       160    Open     Open
5322       150    Open     Open
1038       630    Open     Open
3859       200  Closed   Closed
3187       390    Open     Open
4768       400    Open     Open
1183       500    Open     Open
2445       650    Open     Open
2750       560    Open     Open
3065        50    Open     Open
2721       670    Open     Open
812        650    Open     Open
2687       670    Open     Open
233        510    Open     Open
800        540    Open     Open
5168       240    Open     Open
2834       430    Open     Open
1737       670    Open     Open
538        590    Open     Open
177        540    Open     Open
2458       670    Open     Open
535        480    Open     Open
23         500    Open     Open

In [5]:
resultados_df.to_csv('dados/resultados_modelo3.csv', index=False)